### ISSUE TITLE
Error with nhentai.py module

### ISSUE THREAD

**Issue by hysrx** [hysrx/DoujinGrabber#1]
### Issue
This doesn't appear when using the modified nhentai.py file as a standalone file.

```
Traceback (most recent call last):
  File "dgrab.py", line 410, in <module>
    nh(query)
  File "dgrab.py", line 241, in __init__
    self.init_from_div(arg)
  File "dgrab.py", line 244, in init_from_div
    self.name = res.div.text
AttributeError: 'str' object has no attribute 'div'
```

### Goal
Figure out why `res` resolves as a string

**Comment by hysrx** [comment]
### Fix
The module works like `NHentai(query)`
turns out `query` was a string.

woops

So I just used `int(query)`
